name: coverage

on:
  push:
    branches: [ "*", "task/aws-storage" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -e '.[test]'
    - name: Test with pytest
      run: coverage run -m pytest

    - name: Generate Report
      run: coverage html --omit="*/test*" -d coverage_report
    - name: "Upload HTML report"
      if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: coverage_report
        path: coverage_report


  publish:
    name: Publish report
    needs: build
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout reports repo"
        run: |
          set -xe
          git clone https://${{secrets.REPORT_TOKEN}}@github.com/jhb123/PuzzleServerCoverageReports
          cd PuzzleServerCoverageReports
          git config user.name Joe Briggs
          git config user.email jhbriggs23@gmail.com
          git checkout main
      - name: "download report"
        uses: actions/download-artifact@v3
        with:
          name: coverage_report
          path: PuzzleServerCoverageReports/coverage

      - name: "commit the file"
        run: |
          set -xe
          ls
          cd PuzzleServerCoverageReports
          ls
          git add coverage/* -f
          git commit -m "adds a coverage report"
          git push
